
default_platform(:android)

platform :android do
  # desc "Runs all the tests"
  # lane :distribute do
  #   sh "flutter clean"
  #   sh "flutter build apk --release --flavor development --target lib/main.prod.dart --no-tree-shake-icons"
  #    firebase_app_distribution(
  #           app: "1:852416029288:android:e077dd7fdbb419417b91dd",
  #           testers: "hossammuhammed79@yahoo.com",
  #           android_artifact_type: "APK",
  #           android_artifact_path: "../build/app/outputs/flutter-apk/app-development-release.apk",
  #           firebase_cli_token: "1//039eJiQMC03I-CgYIARAAGAMSNwF-L9IrfYGavBBY244GFafVSWSTbqBlO5oXru9brB7_NIbMYs5FWI6DO6X_L_I52J0NKWVVUxA",
  #           release_notes: "Lots of amazing new features to test out!"
  #       )
  # end
end
